name = "personal-website"
main = "worker.js"
compatibility_date = "2025-01-01"

assets = { directory = "./dist", binding = "ASSETS" }

[vars]
ENVIRONMENT = "production"

[[env.development.vars]]
ENVIRONMENT = "development"
